# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/royal state/PycharmProjects/Serial-Monitor/MainUi.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(730, 420)
        MainWindow.setMinimumSize(QtCore.QSize(730, 200))
        MainWindow.setMaximumSize(QtCore.QSize(750, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.commandEntry = QtWidgets.QLineEdit(self.centralwidget)
        self.commandEntry.setMinimumSize(QtCore.QSize(628, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.commandEntry.setFont(font)
        self.commandEntry.setObjectName("commandEntry")
        self.horizontalLayout.addWidget(self.commandEntry)
        self.sendButton = QtWidgets.QPushButton(self.centralwidget)
        self.sendButton.setMinimumSize(QtCore.QSize(75, 31))
        self.sendButton.setToolTip("")
        self.sendButton.setObjectName("sendButton")
        self.horizontalLayout.addWidget(self.sendButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit.sizePolicy().hasHeightForWidth())
        self.plainTextEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Medium")
        font.setPointSize(10)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setFrameShape(QtWidgets.QFrame.Box)
        self.plainTextEdit.setLineWidth(2)
        self.plainTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout.addWidget(self.plainTextEdit)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.autoScrollCheck = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.autoScrollCheck.sizePolicy().hasHeightForWidth())
        self.autoScrollCheck.setSizePolicy(sizePolicy)
        self.autoScrollCheck.setMinimumSize(QtCore.QSize(70, 0))
        self.autoScrollCheck.setChecked(True)
        self.autoScrollCheck.setObjectName("autoScrollCheck")
        self.horizontalLayout_2.addWidget(self.autoScrollCheck)
        self.showTimeStampCheck = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.showTimeStampCheck.sizePolicy().hasHeightForWidth())
        self.showTimeStampCheck.setSizePolicy(sizePolicy)
        self.showTimeStampCheck.setMinimumSize(QtCore.QSize(111, 0))
        self.showTimeStampCheck.setObjectName("showTimeStampCheck")
        self.horizontalLayout_2.addWidget(self.showTimeStampCheck)
        spacerItem = QtWidgets.QSpacerItem(70, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.outputFormatingCombo = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputFormatingCombo.sizePolicy().hasHeightForWidth())
        self.outputFormatingCombo.setSizePolicy(sizePolicy)
        self.outputFormatingCombo.setMinimumSize(QtCore.QSize(111, 0))
        self.outputFormatingCombo.setObjectName("outputFormatingCombo")
        self.outputFormatingCombo.addItem("")
        self.outputFormatingCombo.addItem("")
        self.outputFormatingCombo.addItem("")
        self.outputFormatingCombo.addItem("")
        self.horizontalLayout_2.addWidget(self.outputFormatingCombo)
        spacerItem1 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.baudRatesCombo = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.baudRatesCombo.sizePolicy().hasHeightForWidth())
        self.baudRatesCombo.setSizePolicy(sizePolicy)
        self.baudRatesCombo.setMinimumSize(QtCore.QSize(91, 0))
        self.baudRatesCombo.setObjectName("baudRatesCombo")
        self.horizontalLayout_2.addWidget(self.baudRatesCombo)
        spacerItem2 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.comPortsCombo = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comPortsCombo.sizePolicy().hasHeightForWidth())
        self.comPortsCombo.setSizePolicy(sizePolicy)
        self.comPortsCombo.setMinimumSize(QtCore.QSize(91, 0))
        self.comPortsCombo.setStatusTip("")
        self.comPortsCombo.setObjectName("comPortsCombo")
        self.horizontalLayout_2.addWidget(self.comPortsCombo)
        spacerItem3 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.connectButton = QtWidgets.QPushButton(self.centralwidget)
        self.connectButton.setMinimumSize(QtCore.QSize(150, 20))
        self.connectButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.connectButton.setCheckable(True)
        self.connectButton.setAutoRepeatDelay(10)
        self.connectButton.setAutoRepeatInterval(10)
        self.connectButton.setObjectName("connectButton")
        self.horizontalLayout_3.addWidget(self.connectButton)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.clearOutputButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clearOutputButton.sizePolicy().hasHeightForWidth())
        self.clearOutputButton.setSizePolicy(sizePolicy)
        self.clearOutputButton.setMinimumSize(QtCore.QSize(81, 20))
        self.clearOutputButton.setToolTip("")
        self.clearOutputButton.setShortcut("")
        self.clearOutputButton.setObjectName("clearOutputButton")
        self.horizontalLayout_3.addWidget(self.clearOutputButton)
        self.resetComPortsButton = QtWidgets.QPushButton(self.centralwidget)
        self.resetComPortsButton.setMaximumSize(QtCore.QSize(25, 20))
        self.resetComPortsButton.setObjectName("resetComPortsButton")
        self.horizontalLayout_3.addWidget(self.resetComPortsButton)
        spacerItem5 = QtWidgets.QSpacerItem(90, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 730, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuSettings = QtWidgets.QMenu(self.menuBar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuBaudRateTextFormat = QtWidgets.QMenu(self.menuSettings)
        self.menuBaudRateTextFormat.setObjectName("menuBaudRateTextFormat")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setMaximumSize(QtCore.QSize(16777215, 15))
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionCommaFormated = QtWidgets.QAction(MainWindow)
        self.actionCommaFormated.setIcon(icon)
        self.actionCommaFormated.setObjectName("actionCommaFormated")
        self.actionNoCommas = QtWidgets.QAction(MainWindow)
        self.actionNoCommas.setObjectName("actionNoCommas")
        self.menuBaudRateTextFormat.addAction(self.actionCommaFormated)
        self.menuBaudRateTextFormat.addAction(self.actionNoCommas)
        self.menuSettings.addAction(self.menuBaudRateTextFormat.menuAction())
        self.menuBar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Serial Monitor"))
        self.commandEntry.setToolTip(_translate("MainWindow", "ENTER YOUR COMMAND"))
        self.sendButton.setText(_translate("MainWindow", "Send"))
        self.sendButton.setShortcut(_translate("MainWindow", "Return"))
        self.autoScrollCheck.setText(_translate("MainWindow", "AutoScroll"))
        self.showTimeStampCheck.setText(_translate("MainWindow", "Show TimeStamp"))
        self.outputFormatingCombo.setItemText(0, _translate("MainWindow", "Both NL & CR"))
        self.outputFormatingCombo.setItemText(1, _translate("MainWindow", "No Line Ending"))
        self.outputFormatingCombo.setItemText(2, _translate("MainWindow", "Newline"))
        self.outputFormatingCombo.setItemText(3, _translate("MainWindow", "Carriage Return"))
        self.baudRatesCombo.setStatusTip(_translate("MainWindow", "Choose Yje"))
        self.connectButton.setToolTip(_translate("MainWindow", "Connect To the Serial Port"))
        self.connectButton.setText(_translate("MainWindow", "CONNECT"))
        self.connectButton.setShortcut(_translate("MainWindow", "F9"))
        self.clearOutputButton.setText(_translate("MainWindow", "Clear Output"))
        self.resetComPortsButton.setToolTip(_translate("MainWindow", "Reset Com Port List"))
        self.resetComPortsButton.setText(_translate("MainWindow", "*R"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuBaudRateTextFormat.setTitle(_translate("MainWindow", "Baud Rate Text Format"))
        self.actionCommaFormated.setText(_translate("MainWindow", "Comma formated"))
        self.actionNoCommas.setText(_translate("MainWindow", "No Commas"))
